# Copyright 2017-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

# Auto-Generated by cargo-ebuild 0.2.0

EAPI=7

CRATES="
aho-corasick-0.5.3
aho-corasick-0.6.3
ansi_term-0.9.0
atty-0.2.2
bitflags-0.7.0
bitflags-0.8.2
clap-2.24.2
clippy-0.0.103
clippy_lints-0.0.103
env_logger-0.3.5
kernel32-sys-0.2.2
lazy_static-0.2.8
libc-0.2.22
log-0.3.7
matches-0.1.4
memchr-0.1.11
memchr-1.0.1
nom-1.2.4
quine-mc_cluskey-0.2.4
racer-2.0.9
rand-0.3.15
regex-0.1.80
regex-0.2.2
regex-syntax-0.3.9
regex-syntax-0.4.1
rustc-serialize-0.3.24
semver-0.2.3
strsim-0.6.0
syntex_errors-0.52.0
syntex_pos-0.52.0
syntex_syntax-0.52.0
term-0.4.5
term_size-0.3.0
thread-id-2.0.0
thread-id-3.1.0
thread_local-0.2.7
thread_local-0.3.3
toml-0.1.30
toml-0.2.1
typed-arena-1.3.0
unicode-normalization-0.1.4
unicode-segmentation-1.2.0
unicode-width-0.1.4
unicode-xid-0.0.3
unreachable-0.1.1
utf8-ranges-0.1.3
utf8-ranges-1.0.0
vec_map-0.8.0
void-1.0.2
winapi-0.2.8
winapi-build-0.1.1
"

inherit cargo

DESCRIPTION="Code completion for Rust"
HOMEPAGE="https://github.com/phildawes/racer"
SRC_URI="$(cargo_crate_uris ${CRATES})"
RESTRICT="mirror"
LICENSE="MIT" # Update to proper Gentoo format
SLOT="0"
KEYWORDS="~amd64"
IUSE=""

DEPEND=""
RDEPEND=""
